name: actions

on: [push]

env:
  python-version: 3.7

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint with pysen
        run: |
          pysen run lint
